---
- name: update configuration
  include_tasks: config.yml file={{ conf.key }} config={{ conf.value }}
  with_dict: "{{ automysqlbackup_conf }}"
  loop_control:
    loop_var: conf
  when: automysqlbackup_conf is defined
