---
- name: update configuration
  include_tasks:
    file: config.yml
    apply:
      vars:
        file: "{{ config.key }}"
        config: "{{ config.value }}"
  loop: "{{ automysqlbackup_conf | dict2items }}"
  loop_control:
    loop_var: config
  when: automysqlbackup_conf is defined
